### ISSUE TITLE
how to find address?

### ISSUE THREAD

**Issue by zufan-yp** [Eirxne/Valorant-Aim-ESP-Hack#1]
![image](https://user-images.githubusercontent.com/78656480/127202341-bdf83aa3-49fd-4f66-adf3-45fd10b9c729.png)

**Comment by stefanodvx** [comment]
hi bro, you fixed this?

**Comment by GuestOfficial** [comment]
> hi bro, you fixed this?

For me i didnt, can you help me ? i'm new in this :)

**Comment by Rubiooo04** [comment]
open a valorant game

**Comment by mzahh** [comment]
//map your memory driver

**Comment by swopshawn** [comment]
This issue is also happening for me, I still don't know what to do to fix this.
